import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.about': 'Tentang Kami',
    'nav.farming': 'Sistem Budidaya',
    'nav.training': 'Pelatihan Online',
    'nav.products': 'Produk',
    'nav.education': 'Edukasi',
    'nav.contact': 'Kontak',
    
    // Hero Section
    'hero.tagline': 'Dari Alam Nusantara ke Pasar Dunia — Inovasi Budidaya Sidat Terpadu',
    'hero.subtitle': 'Kuasai sistem budidaya sidat berstandar ekspor, ikuti pelatihan bersama ahli, dan hadirkan produk unggulan untuk pasar lokal dan global',
    'hero.cta1': 'Beli Sekarang',
    'hero.cta2': 'Daftar Pelatihan',
    'hero.cta3': 'Pelajari Sistem',
    'hero.cta4': 'Tanya Robot Pintar',
    'hero.innovation': '🌊 Inovasi Budidaya Berkelanjutan',
    'hero.cta.start': 'Mulai Sekarang',
    'hero.cta.final': 'Mulai Perjalanan Budidaya Sidat Anda Hari Ini',
    'hero.cta.subtitle': 'Bergabung dengan ribuan petani sukses yang telah merasakan keuntungan budidaya sidat modern.',
    
    // Home Page Features
    'features.badge': '✨ Keunggulan Kami',
    'features.title': 'Mengapa Memilih Sidat Sangkuriang?',
    'features.subtitle': 'Kami memberikan solusi terlengkap untuk budidaya sidat modern yang berkelanjutan dan menguntungkan.',
    'features.item1.title': 'Teknologi Berkelanjutan',
    'features.item1.desc': 'Sistem budidaya ramah lingkungan dengan teknologi terdepan untuk hasil optimal dan sustainable.',
    'features.item2.title': 'Pelatihan Ahli',
    'features.item2.desc': 'Belajar dari praktisi berpengalaman 20+ tahun di industri budidaya sidat Indonesia.',
    'features.item3.title': 'Kualitas Premium',
    'features.item3.desc': 'Produk sidat bersertifikat halal dan standar ekspor internasional.',
    'home.feature1.title': 'Teknologi Modern',
    'home.feature1.desc': 'Sistem budidaya ramah lingkungan dengan teknologi terdepan untuk hasil optimal dan sustainable.',
    'home.feature2.title': 'Pelatihan Ahli',
    'home.feature2.desc': 'Belajar dari praktisi berpengalaman 20+ tahun di industri budidaya sidat Indonesia.',
    'home.feature3.title': 'Kualitas Premium',
    'home.feature3.desc': 'Produk sidat bersertifikat halal dan standar ekspor internasional.',
    
    // Products
    'products.title': 'Produk Kami',
    'products.subtitle': 'Nikmati kelezatan sidat segar dan olahan berkualitas premium',
    'products.fresh': 'Sidat Segar',
    'products.processed': 'Sidat Olahan',
    'products.addToCart': 'Tambah ke Keranjang',
    'products.buyNow': 'Beli Sekarang',
    'products.all': 'Semua Produk',
    'products.category.fresh': 'Sidat Segar',
    'products.category.processed': 'Sidat Olahan',
    'products.whatsapp': 'Pesan via WhatsApp',
    'products.consultation.title': 'Butuh Konsultasi Produk?',
    'products.consultation.desc': 'Tim ahli kami siap membantu Anda memilih produk yang tepat sesuai kebutuhan.',
    'products.consultation.button': 'Hubungi Ahli Kami',
    
    // Training
    'training.title': 'Pelatihan Online',
    'training.subtitle': 'Kuasai teknik budidaya sidat modern dengan panduan ahli',
    'training.enroll': 'Daftar Sekarang',
    'training.badge': '🎓 Pelatihan Profesional',
    'training.curriculum': '📚 KURIKULUM LENGKAP',
    'training.curriculum.title': 'Kurikulum Pelatihan',
    'training.curriculum.subtitle': 'Program pembelajaran terstruktur dengan 6 modul komprehensif untuk menguasai budidaya sidat modern',
    'training.curriculum.module': 'Modul',
    'training.curriculum.desc1': 'Memahami dasar-dasar biologi sidat, siklus hidup, dan prinsip-prinsip budidaya yang berkelanjutan.',
    'training.curriculum.desc2': 'Desain dan konstruksi kolam modern, sistem filtrasi, aerasi, dan infrastruktur pendukung.',
    'training.curriculum.desc3': 'Formula pakan optimal, jadwal pemberian, dan manajemen nutrisi untuk pertumbuhan maksimal.',
    'training.curriculum.desc4': 'Pencegahan penyakit, diagnosis dini, pengobatan, dan manajemen kesehatan kolam.',
    'training.curriculum.desc5': 'Teknik panen yang tepat, penanganan pasca panen, dan standar kualitas produk.',
    'training.curriculum.desc6': 'Strategi pemasaran, analisis bisnis, manajemen keuangan, dan pengembangan usaha.',
    'training.features.badge': '✨ Keunggulan Program',
    'training.features.title': 'Mengapa Memilih Pelatihan Kami?',
    'training.features.subtitle': 'Program pelatihan terlengkap dengan metode pembelajaran modern dan bimbingan ahli',
    'training.curriculum.stats.modules': 'Modul Pembelajaran',
    'training.curriculum.stats.hours': 'Jam Pelatihan',
    'training.curriculum.stats.practice': 'Praktik Langsung',
    'training.curriculum.stats.access': 'Akses Selamanya',
    'training.features.flexible.title': 'Fleksibel',
    'training.features.flexible.desc': 'Belajar kapan saja sesuai jadwal Anda',
    'training.features.video.title': 'Video HD',
    'training.features.video.desc': 'Materi berkualitas tinggi',
    'training.features.certificate.title': 'Sertifikat',
    'training.features.certificate.desc': 'Sertifikat resmi tersedia',
    'training.features.mentoring.title': 'Mentoring',
    'training.features.mentoring.desc': 'Bimbingan langsung ahli',
    'training.cta.title': 'Siap Memulai Perjalanan Anda?',
    'training.cta.subtitle': 'Bergabunglah dengan ribuan petani sukses yang telah mengikuti program pelatihan kami',
    'training.cta.register': 'Daftar Sekarang',
    'training.cta.learn': 'Pelajari Lebih Lanjut',
    'training.students': 'siswa',
    'training.whatsapp': 'Hubungi via Whatsapp',

    
    // Education
    'education.badge': '📚 Pusat Edukasi',
    'education.title': 'Pusat Edukasi',
    'education.subtitle': 'Pelajari segala hal tentang budidaya sidat melalui artikel, video, dan panduan praktis dari para ahli.',
    'education.categories.basic.title': 'Panduan Dasar',
    'education.categories.basic.desc': 'Pelajari dasar-dasar budidaya sidat untuk pemula',
    'education.categories.video.title': 'Video Tutorial',
    'education.categories.video.desc': 'Tutorial video step-by-step dari para ahli',
    'education.categories.articles.title': 'Artikel & Tips',
    'education.categories.articles.desc': 'Artikel mendalam dan tips praktis budidaya',
    'education.featured': 'Featured Article',
    'education.featured.title': 'Revolusi Budidaya Sidat: Dari Tradisional ke Digital',
    'education.featured.desc': 'Temukan bagaimana transformasi digital mengubah lanskap budidaya sidat di Indonesia, membuatnya lebih efisien, berkelanjutan, dan menguntungkan dari sebelumnya.',
    'education.featured.readArticle': 'Baca Artikel',
    'education.readArticle': 'Baca Artikel',
    'education.articles': 'Artikel Terbaru',
    'education.articles.title': 'Artikel Terbaru',
    'education.articles.readMore': 'Baca Selengkapnya',
    'education.videos': 'Video Tutorial',
    'education.videos.title': 'Video Tutorial',
    'education.videos.watch': 'Tonton Video',
    'education.watchVideo': 'Tonton Video',
    'education.certificate.title': 'Dapatkan Sertifikat Ahli',
    'education.certificate.desc': 'Ikuti program sertifikasi kami dan dapatkan pengakuan resmi sebagai ahli budidaya sidat.',
    'education.certificate.button': 'Mulai Sertifikasi',
    'education.certification.title': 'Dapatkan Sertifikat Ahli',
    'education.certification.description': 'Ikuti program sertifikasi kami dan dapatkan pengakuan resmi sebagai ahli budidaya sidat.',
    'education.certification.start': 'Mulai Sertifikasi',
    
    // About
    'about.badge': '🏢 Tentang Kami',
    'about.title': 'Tentang Sidat Sangkuriang',
    'about.subtitle': 'Pelopor teknologi budidaya sidat modern di Indonesia dengan komitmen pada inovasi dan keberlanjutan',
    'about.stats.experience': 'Tahun Pengalaman',
    'about.stats.farmers': 'Peternak Terdaftar',
    'about.stats.cities': 'Kota Terjangkau',
    'about.stats.satisfaction': 'Tingkat Kepuasan',
    'about.values.title': 'Nilai-Nilai Kami',
    'about.values.innovation': 'Inovasi Berkelanjutan',
    'about.values.innovation.title': 'Inovasi',
    'about.values.innovation.desc': 'Mengembangkan teknologi terdepan untuk budidaya sidat modern',
    'about.values.empowerment': 'Pemberdayaan Petani',
    'about.values.empowerment.title': 'Pemberdayaan',
    'about.values.empowerment.desc': 'Memberdayakan petani lokal dengan pengetahuan dan teknologi',
    'about.values.quality': 'Kualitas Premium',
    'about.values.quality.title': 'Kualitas',
    'about.values.quality.desc': 'Mengutamakan kualitas produk dan layanan terbaik',
    'about.values.technology': 'Teknologi Terdepan',
    'about.values.technology.title': 'Teknologi',
    'about.values.technology.desc': 'Memanfaatkan teknologi IoT untuk efisiensi maksimal',
    'about.team.title': 'Tim Ahli Kami',
    'about.team.member1.name': 'Dr. Ahmad Santoso',
    'about.team.member1.role': 'Direktur Utama',
    'about.team.member1.desc': 'Ahli budidaya sidat dengan pengalaman 15 tahun',
    'about.team.member2.name': 'Ir. Sari Dewi',
    'about.team.member2.role': 'Kepala Teknologi',
    'about.team.member2.desc': 'Spesialis sistem IoT dan otomasi pertanian',
    'about.team.member3.name': 'Prof. Budi Hartono',
    'about.team.member3.role': 'Konsultan Ahli',
    'about.team.member3.desc': 'Pakar akuakultur dan pengembangan produk',
    'about.mission.title': 'Misi Kami',
    'about.mission.desc': 'Menjadikan Indonesia sebagai pusat budidaya sidat dunia melalui inovasi teknologi, pemberdayaan petani, dan produk berkualitas tinggi yang berdampak positif bagi ekonomi dan lingkungan.',
    
    // Farming
    'farming.badge': '🌊 Smart Farming',
    'farming.title': 'Sistem Budidaya Modern',
    'farming.subtitle': 'Teknologi budidaya sidat terdepan dengan sistem monitoring terintegrasi dan otomasi penuh untuk hasil maksimal.',
    'farming.features.title': 'Fitur Sistem Unggulan',
    'farming.features.water.title': 'Monitoring Kualitas Air',
    'farming.features.water.desc': 'Pemantauan pH, oksigen, dan parameter air secara real-time',
    'farming.features.temperature.title': 'Kontrol Suhu Otomatis',
    'farming.features.temperature.desc': 'Sistem pengaturan suhu otomatis untuk kondisi optimal',
    'farming.features.aeration.title': 'Sistem Aerasi Cerdas',
    'farming.features.aeration.desc': 'Pengaturan aerasi otomatis berdasarkan kebutuhan oksigen',
    'farming.features.monitoring.title': 'Dashboard Monitoring',
    'farming.features.monitoring.desc': 'Pantau semua parameter dari satu dashboard terpusat',
    'farming.features.feeding.title': 'Pemberian Pakan Otomatis',
    'farming.features.feeding.desc': 'Sistem pemberian pakan terjadwal dengan porsi optimal',
    'farming.features.biosecurity.title': 'Keamanan Biosekuriti',
    'farming.features.biosecurity.desc': 'Sistem keamanan untuk mencegah kontaminasi dan penyakit',
    'farming.dashboard.title': 'Dashboard Monitoring Real-time',
    'farming.dashboard.subtitle': 'Pantau kondisi kolam Anda 24/7 dari mana saja',
    'farming.cta.title': 'Siap Memulai Budidaya Modern?',
    'farming.cta.subtitle': 'Konsultasi gratis dengan ahli kami untuk mendesain sistem budidaya sesuai kebutuhan Anda.',
    'farming.cta.button': 'Konsultasi Gratis',
    
    // Contact
    'contact.title': 'Hubungi Kami',
    'contact.subtitle': 'Tim ahli kami siap membantu Anda dengan segala pertanyaan tentang budidaya sidat, pelatihan, dan produk kami.',
    'contact.office': 'Alamat Kantor',
    'contact.phone': 'Telepon',
    'contact.email': 'Email',
    'contact.hours': 'Jam Operasional',
    'contact.hours.content': 'Senin - Jumat: 08:00 - 17:00 WIB\nSabtu: 08:00 - 15:00 WIB',
    'contact.whatsapp.title': 'WhatsApp Konsultasi',
    'contact.whatsapp.desc': 'Chat langsung dengan ahli kami',
    'contact.whatsapp.button': 'Chat Sekarang',
    'contact.visit.title': 'Kunjungan Lapangan',
    'contact.visit.desc': 'Jadwalkan kunjungan ke fasilitas kami',
    'contact.visit.button': 'Jadwalkan',
    'contact.form.title': 'Kirim Pesan',
    'contact.form.name': 'Nama Lengkap',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Nomor Telepon',
    'contact.form.subject': 'Subjek',
    'contact.form.message': 'Pesan',
    'contact.form.send': 'Kirim Pesan',
    'contact.form.success': 'Pesan terkirim! Tim kami akan segera menghubungi Anda.',
    'contact.location': 'Lokasi Kami',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.badge': '🛒 Checkout Aman',
    'checkout.items': 'Item Pesanan',
    'checkout.empty': 'Keranjang Anda kosong. Mari mulai berbelanja!',
    'checkout.emptyCart': 'Keranjang Anda kosong. Mari mulai berbelanja!',
    'checkout.viewProducts': 'Lihat Produk',
    'checkout.orderItems': 'Item Pesanan',
    'checkout.paymentInfo': 'Informasi Pembayaran',
    'checkout.customerData': 'Data Pelanggan',
    'checkout.fullName': 'Nama Lengkap',
    'checkout.email': 'Email',
    'checkout.phone': 'Nomor Telepon',
    'checkout.address': 'Alamat Lengkap',
    'checkout.paymentMethod': 'Metode Pembayaran',
    'checkout.creditCard': 'Kartu Kredit/Debit (Stripe)',
    'checkout.bankTransfer': 'Transfer Bank',
    'checkout.securityNotice': 'Pembayaran Anda aman dan terenkripsi. Kami tidak menyimpan informasi kartu kredit.',
    'checkout.payNow': 'Bayar Sekarang',
    'checkout.purchaseSuccess': 'Pembelian berhasil! Tim kami akan menghubungi Anda segera.',
    'checkout.customerInfo': 'Informasi Pelanggan',
    'checkout.payment': 'Metode Pembayaran',
    'checkout.summary': 'Ringkasan Pesanan',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Ongkos Kirim',
    'checkout.tax': 'Pajak',
    'checkout.total': 'Total Pembayaran',
    'checkout.placeOrder': 'Buat Pesanan',
    'checkout.success': 'Pembelian berhasil! Tim kami akan menghubungi Anda segera.',
    'checkout.name.placeholder': 'Masukkan nama lengkap',
    'checkout.email.placeholder': 'Masukkan email',
    'checkout.phone.placeholder': 'Masukkan nomor telepon',
    'checkout.address.placeholder': 'Masukkan alamat lengkap',
    
    // Common
    'common.learnMore': 'Pelajari Lebih Lanjut',
    'common.cart': 'Keranjang',
    'common.checkout': 'Checkout',
    'common.total': 'Total',
    'common.currency': 'IDR',
    'common.quantity': 'Jumlah',
    'common.remove': 'Hapus',
    'common.update': 'Perbarui',
    'common.continue': 'Lanjutkan',
    'common.back': 'Kembali',
    'common.next': 'Selanjutnya',
    'common.previous': 'Sebelumnya',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.loading': 'Memuat...',
    'common.error': 'Terjadi kesalahan',
    'common.success': 'Berhasil',
    'common.warning': 'Peringatan',
    'common.info': 'Informasi',
    
    // Chat Assistant
    'chat.title': 'Robot Pintar Sidat',
    'chat.placeholder': 'Tanyakan tentang budidaya sidat...',
    'chat.send': 'Kirim',
    'chat.greeting': 'Halo! Saya Robot Pintar Sidat. Saya siap membantu Anda dengan pertanyaan tentang budidaya sidat, pelatihan, atau produk kami. Silakan tanya apa saja!',
    'chat.farming': 'Sistem budidaya sidat kami menggunakan teknologi modern dengan kontrol kualitas air otomatis, sistem aerasi canggih, dan monitoring 24/7. Kami dapat membantu Anda memulai dari skala kecil hingga komersial.',
    'chat.training': 'Pelatihan online kami mencakup teori dan praktik budidaya sidat, manajemen kolam, nutrisi, dan pemasaran. Durasi 6 minggu dengan sertifikat resmi.',
    'chat.products': 'Kami menyediakan sidat segar grade A dan berbagai olahan seperti unagi, kabayaki, dan produk frozen. Semua produk sudah tersertifikat halal.',
    'chat.default': 'Terima kasih atas pertanyaannya! Tim ahli kami akan segera memberikan informasi yang Anda butuhkan. Untuk pertanyaan mendetail, silakan hubungi WhatsApp kami.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.farming': 'Farming System',
    'nav.training': 'Online Training',
    'nav.products': 'Products',
    'nav.education': 'Education',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.tagline': 'From Indonesian Nature to Global Markets — Integrated Eel Farming Innovation',
    'hero.subtitle': 'Master export-standard eel farming systems, join expert training, and deliver premium products for local and global markets',
    'hero.cta1': 'Buy Now',
    'hero.cta2': 'Join Training',
    'hero.cta3': 'Learn System',
    'hero.cta4': 'Ask Smart Robot',
    'hero.innovation': '🌊 Sustainable Farming Innovation',
    'hero.cta.start': 'Get Started',
    'hero.cta.final': 'Start Your Eel Farming Journey Today',
    'hero.cta.subtitle': 'Join thousands of successful farmers who have experienced the benefits of modern eel farming.',
    
    // Home Page Features
    'features.badge': '✨ Our Excellence',
    'features.title': 'Why Choose Sidat Sangkuriang?',
    'features.subtitle': 'We provide the most complete solution for modern eel farming that is sustainable and profitable.',
    'features.item1.title': 'Sustainable Technology',
    'features.item1.desc': 'Environmentally friendly farming system with cutting-edge technology for optimal and sustainable results.',
    'features.item2.title': 'Expert Training',
    'features.item2.desc': 'Learn from practitioners with 20+ years of experience in Indonesian eel farming industry.',
    'features.item3.title': 'Premium Quality',
    'features.item3.desc': 'Halal certified eel products and international export standards.',
    'home.feature1.title': 'Modern Technology',
    'home.feature1.desc': 'Environmentally friendly farming system with cutting-edge technology for optimal and sustainable results.',
    'home.feature2.title': 'Expert Training',
    'home.feature2.desc': 'Learn from practitioners with 20+ years of experience in Indonesian eel farming industry.',
    'home.feature3.title': 'Premium Quality',
    'home.feature3.desc': 'Halal certified eel products and international export standards.',
    
    // Products
    'products.title': 'Our Products',
    'products.subtitle': 'Enjoy the deliciousness of fresh and premium processed eel',
    'products.fresh': 'Fresh Eel',
    'products.processed': 'Processed Eel',
    'products.addToCart': 'Add to Cart',
    'products.buyNow': 'Buy Now',
    'products.all': 'All Products',
    'products.category.fresh': 'Fresh Eel',
    'products.category.processed': 'Processed Eel',
    'products.whatsapp': 'Order via WhatsApp',
    'products.consultation.title': 'Need Product Consultation?',
    'products.consultation.desc': 'Our expert team is ready to help you choose the right products according to your needs.',
    'products.consultation.button': 'Contact Our Experts',
    
    // Training
    'training.title': 'Online Training',
    'training.subtitle': 'Master modern eel farming techniques with expert guidance',
    'training.enroll': 'Enroll Now',
    'training.badge': '🎓 Professional Training',
    'training.curriculum': '📚 COMPLETE CURRICULUM',
    'training.curriculum.title': 'Training Curriculum',
    'training.curriculum.subtitle': 'Structured learning program with 6 comprehensive modules to master modern eel farming',
    'training.curriculum.module': 'Module',
    'training.curriculum.desc1': 'Understanding eel biology basics, life cycle, and sustainable farming principles.',
    'training.curriculum.desc2': 'Modern pond design and construction, filtration systems, aeration, and supporting infrastructure.',
    'training.curriculum.desc3': 'Optimal feed formulation, feeding schedules, and nutrition management for maximum growth.',
    'training.curriculum.desc4': 'Disease prevention, early diagnosis, treatment, and pond health management.',
    'training.curriculum.desc5': 'Proper harvesting techniques, post-harvest handling, and product quality standards.',
    'training.curriculum.desc6': 'Marketing strategies, business analysis, financial management, and business development.',
    'training.features.badge': '✨ Program Excellence',
    'training.features.title': 'Why Choose Our Training?',
    'training.features.subtitle': 'Most comprehensive training program with modern learning methods and expert guidance',
    'training.curriculum.stats.modules': 'Learning Modules',
    'training.curriculum.stats.hours': 'Training Hours',
    'training.curriculum.stats.practice': 'Hands-on Practice',
    'training.curriculum.stats.access': 'Lifetime Access',
    'training.features.flexible.title': 'Flexible',
    'training.features.flexible.desc': 'Learn anytime according to your schedule',
    'training.features.video.title': 'HD Video',
    'training.features.video.desc': 'High quality materials',
    'training.features.certificate.title': 'Certificate',
    'training.features.certificate.desc': 'Official certificate available',
    'training.features.mentoring.title': 'Mentoring',
    'training.features.mentoring.desc': 'Direct expert guidance',
    'training.cta.title': 'Ready to Start Your Journey?',
    'training.cta.subtitle': 'Join thousands of successful farmers who have taken our training program',
    'training.cta.register': 'Register Now',
    'training.cta.learn': 'Learn More',
    'training.students': 'students',
    'training.whatsapp': 'Contact via WhatsApp',

    
    // Education
    'education.badge': '📚 Education Center',
    'education.title': 'Education Center',
    'education.subtitle': 'Learn everything about eel farming through articles, videos, and practical guides from experts.',
    'education.categories.basic.title': 'Basic Guide',
    'education.categories.basic.desc': 'Learn the basics of eel farming for beginners',
    'education.categories.video.title': 'Video Tutorials',
    'education.categories.video.desc': 'Step-by-step video tutorials from experts',
    'education.categories.articles.title': 'Articles & Tips',
    'education.categories.articles.desc': 'In-depth articles and practical farming tips',
    'education.featured': 'Featured Article',
    'education.featured.title': 'Eel Farming Revolution: From Traditional to Digital',
    'education.featured.desc': 'Discover how digital transformation is changing the eel farming landscape in Indonesia, making it more efficient, sustainable, and profitable than ever before.',
    'education.featured.readArticle': 'Read Article',
    'education.readArticle': 'Read Article',
    'education.articles': 'Latest Articles',
    'education.articles.title': 'Latest Articles',
    'education.articles.readMore': 'Read More',
    'education.videos': 'Video Tutorials',
    'education.videos.title': 'Video Tutorials',
    'education.videos.watch': 'Watch Video',
    'education.watchVideo': 'Watch Video',
    'education.certificate.title': 'Get Expert Certificate',
    'education.certificate.desc': 'Join our certification program and get official recognition as an eel farming expert.',
    'education.certificate.button': 'Start Certification',
    'education.certification.title': 'Get Expert Certificate',
    'education.certification.description': 'Join our certification program and get official recognition as an eel farming expert.',
    'education.certification.start': 'Start Certification',
    
    // About
    'about.badge': '🏢 About Us',
    'about.title': 'About Sidat Sangkuriang',
    'about.subtitle': 'Pioneer of modern eel farming technology in Indonesia with commitment to innovation and sustainability',
    'about.stats.experience': 'Years Experience',
    'about.stats.farmers': 'Registered Farmers',
    'about.stats.cities': 'Cities Reached',
    'about.stats.satisfaction': 'Satisfaction Rate',
    'about.values.title': 'Our Values',
    'about.values.innovation': 'Sustainable Innovation',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Developing cutting-edge technology for modern eel farming',
    'about.values.empowerment': 'Farmer Empowerment',
    'about.values.empowerment.title': 'Empowerment',
    'about.values.empowerment.desc': 'Empowering local farmers with knowledge and technology',
    'about.values.quality': 'Premium Quality',
    'about.values.quality.title': 'Quality',
    'about.values.quality.desc': 'Prioritizing the best product and service quality',
    'about.values.technology': 'Leading Technology',
    'about.values.technology.title': 'Technology',
    'about.values.technology.desc': 'Utilizing IoT technology for maximum efficiency',
    'about.team.title': 'Our Expert Team',
    'about.team.member1.name': 'Dr. Ahmad Santoso',
    'about.team.member1.role': 'Chief Executive Officer',
    'about.team.member1.desc': 'Eel farming expert with 15 years of experience',
    'about.team.member2.name': 'Ir. Sari Dewi',
    'about.team.member2.role': 'Chief Technology Officer',
    'about.team.member2.desc': 'IoT systems and agricultural automation specialist',
    'about.team.member3.name': 'Prof. Budi Hartono',
    'about.team.member3.role': 'Expert Consultant',
    'about.team.member3.desc': 'Aquaculture and product development expert',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'Making Indonesia the world center of eel farming through technological innovation, farmer empowerment, and high-quality products that positively impact the economy and environment.',
    
    // Farming
    'farming.badge': '🌊 Smart Farming',
    'farming.title': 'Modern Farming System',
    'farming.subtitle': 'Leading eel farming technology with integrated monitoring system and full automation for maximum results.',
    'farming.features.title': 'Outstanding System Features',
    'farming.features.water.title': 'Water Quality Monitoring',
    'farming.features.water.desc': 'Real-time monitoring of pH, oxygen, and water parameters',
    'farming.features.temperature.title': 'Automatic Temperature Control',
    'farming.features.temperature.desc': 'Automatic temperature regulation system for optimal conditions',
    'farming.features.aeration.title': 'Smart Aeration System',
    'farming.features.aeration.desc': 'Automatic aeration control based on oxygen requirements',
    'farming.features.monitoring.title': 'Monitoring Dashboard',
    'farming.features.monitoring.desc': 'Monitor all parameters from one centralized dashboard',
    'farming.features.feeding.title': 'Automatic Feeding System',
    'farming.features.feeding.desc': 'Scheduled feeding system with optimal portions',
    'farming.features.biosecurity.title': 'Biosecurity Safety',
    'farming.features.biosecurity.desc': 'Security system to prevent contamination and diseases',
    'farming.dashboard.title': 'Real-time Monitoring Dashboard',
    'farming.dashboard.subtitle': 'Monitor your pond conditions 24/7 from anywhere',
    'farming.cta.title': 'Ready to Start Modern Farming?',
    'farming.cta.subtitle': 'Free consultation with our experts to design farming systems according to your needs.',
    'farming.cta.button': 'Free Consultation',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Our expert team is ready to help you with any questions about eel farming, training, and our products.',
    'contact.office': 'Office Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Operating Hours',
    'contact.hours.content': 'Monday - Friday: 08:00 - 17:00 WIB\nSaturday: 08:00 - 15:00 WIB',
    'contact.whatsapp.title': 'WhatsApp Consultation',
    'contact.whatsapp.desc': 'Chat directly with our experts',
    'contact.whatsapp.button': 'Chat Now',
    'contact.visit.title': 'Field Visit',
    'contact.visit.desc': 'Schedule a visit to our facilities',
    'contact.visit.button': 'Schedule',
    'contact.form.title': 'Send Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.success': 'Message sent! Our team will contact you soon.',
    'contact.location': 'Our Location',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.badge': '🛒 Secure Checkout',
    'checkout.items': 'Order Items',
    'checkout.empty': 'Your cart is empty. Let\'s start shopping!',
    'checkout.emptyCart': 'Your cart is empty. Let\'s start shopping!',
    'checkout.viewProducts': 'View Products',
    'checkout.orderItems': 'Order Items',
    'checkout.paymentInfo': 'Payment Information',
    'checkout.customerData': 'Customer Data',
    'checkout.fullName': 'Full Name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone Number',
    'checkout.address': 'Complete Address',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.creditCard': 'Credit/Debit Card (Stripe)',
    'checkout.bankTransfer': 'Bank Transfer',
    'checkout.securityNotice': 'Your payment is secure and encrypted. We do not store credit card information.',
    'checkout.payNow': 'Pay Now',
    'checkout.purchaseSuccess': 'Purchase successful! Our team will contact you soon.',
    'checkout.customerInfo': 'Customer Information',
    'checkout.payment': 'Payment Method',
    'checkout.summary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Shipping',
    'checkout.tax': 'Tax',
    'checkout.total': 'Total Payment',
    'checkout.placeOrder': 'Place Order',
    'checkout.success': 'Purchase successful! Our team will contact you soon.',
    'checkout.name.placeholder': 'Enter full name',
    'checkout.email.placeholder': 'Enter email',
    'checkout.phone.placeholder': 'Enter phone number',
    'checkout.address.placeholder': 'Enter complete address',
    
    // Common
    'common.learnMore': 'Learn More',
    'common.cart': 'Cart',
    'common.checkout': 'Checkout',
    'common.total': 'Total',
    'common.currency': 'USD',
    'common.quantity': 'Quantity',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    
    // Chat Assistant
    'chat.title': 'Eel Smart Robot',
    'chat.placeholder': 'Ask about eel farming...',
    'chat.send': 'Send',
    'chat.greeting': 'Hello! I am the Eel Smart Robot. I am ready to help you with questions about eel farming, training, or our products. Please ask anything!',
    'chat.farming': 'Our eel farming system uses modern technology with automatic water quality control, advanced aeration systems, and 24/7 monitoring. We can help you start from small scale to commercial.',
    'chat.training': 'Our online training covers theory and practice of eel farming, pond management, nutrition, and marketing. Duration is 6 weeks with official certificate.',
    'chat.products': 'We provide grade A fresh eel and various processed products like unagi, kabayaki, and frozen products. All products are halal certified.',
    'chat.default': 'Thank you for your question! Our expert team will soon provide the information you need. For detailed questions, please contact our WhatsApp.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['id']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};